server:
  port: 8080

spring:
  config:
    import:
      - application-jwt.yml
      - application-oauth.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nawabari-db.c5ixtmjnfhyv.ap-northeast-2.rds.amazonaws.com:3306/nawabariserverTimezone=UTC&characterEncoding=UTF-8serverTimezone=UTC&characterEncoding=UTF-8
    username: sungmin
    password: dta310ab

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true

cloud:
  aws:
    s3:
      bucket: nawabari-images-bucket
    credentials:
      access-key: AKIAXO4UJX62S6HSLKTW
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type: trace