## .gitignore

  /src/main/resources/application.yml

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/NawaBari?serverTimezone=UTC&characterEncoding=UTF-8
    username: sungmin
    password: krsm59@@

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

    security:
      oauth2:
        client:
          registration:

            kakao:
              client-id: 27eb3015ee913717948781cb023560f3
              client-secret: lt1sYaxEldLtR5M5Fb6E6jwDDKuZpSa4
              redirect-uri: http://localhost:8080/login
              client-authentication-method: POST
              authorization-grant-type: authorization_code
              scope: id, profile_nickname, profile_image, gender, age_range
              client-name: Kakao

              provider:
                kakao:
                  authorization-uri: https://kauth.kakao.com/oauth/authorize
                  token-uri: https://kauth.kakao.com/oauth/token
                  user-info-uri: https://kapi.kakao.com/v2/user/me
                  user-name-attribute: id


jwt:
  secretKey: E47G7VwD0Sx+7V0yWdZY8enVwdjz9xC4EadGZzid/2s=

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh
